# 다중 로지스틱 회귀

- 변수 2개: 학습 시간, 과외 횟수
- 합격여부 (Y)	0	0	0	1	1	1	1
- 학습시간 (X1)	2	4	6	8	10	12	14
- 과외횟수 (X2)	3	3	4	6	7	8	9

In [1]:
# 필요한 라이브러리  # 텐서플로어 1으로 작동함
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
seed = 0
np.random.seed(seed)
tf.set_random_seed(seed)

In [3]:
# x, y의 데이터 값
x_data = np.array([[2,3],[4,3],[6,4],[8,6],[10,7],[12,8],[14,9]])
y_data = np.array([0,0,0,1,1,1,1]).reshape(7,1)

In [4]:
x_data, y_data

(array([[ 2,  3],
        [ 4,  3],
        [ 6,  4],
        [ 8,  6],
        [10,  7],
        [12,  8],
        [14,  9]]),
 array([[0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [1]]))

In [5]:
print(x_data.shape, y_data.shape)

(7, 2) (7, 1)


In [6]:
# 입력 값을 플레이스 홀더에 저장
X = tf.placeholder(tf.float64, shape=[None, 2])
Y = tf.placeholder(tf.float64, shape=[None, 1])

In [7]:
# 웨이트 a와 바이어스 b의 값을 임의로 정함
w = tf.Variable(tf.random_uniform([2,1], dtype=tf.float64))
# [2,1] 의미: 들어오는 값은 2개, 나가는 값은 1개
b = tf.Variable(tf.random_uniform([1], dtype=tf.float64))

In [8]:
# y 시그모이드 함수의 방정식을 세움
yhat = tf.sigmoid(tf.matmul(X, w) + b)

In [9]:
# 오차를 구하는 함수 (그냥 외워라) 
# binary cross entropy / categorical creoss entropy
loss = - tf.reduce_mean(Y*tf.log(yhat)+(1-Y)*tf.log(1-yhat))

In [10]:
# 학습률 값
learning_rate=0.1

In [11]:
# 오차를 최소로 하는 값 찾기
gradient_decent = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)

In [12]:
predicted = tf.cast(yhat>0.5, dtype=tf.float64)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float64))

In [15]:
# 학습
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for i in range(3001):
        w_, b_, loss_, _ = sess.run([w, b, loss, gradient_decent], feed_dict={X: x_data, Y: y_data})
        if (i + 1) % 300 == 0:
            print("step=%d, w1=%.4f, w2=%.4f, b=%.4f, loss=%.4f" % 
                  (i + 1, w_[0], w_[1], b_, loss_))

# 어떻게 활용하는가
    new_x = np.array([7, 6.]).reshape(1, 2)  # [7, 6]은 각각 공부한 시간과 과외 수업 횟수
    new_y = sess.run(Y, feed_dict={X: new_x})

    print("공부한 시간: %d, 과외 수업 횟수: %d" % (new_x[:,0], new_x[:,1]))
    print("합격 가능성: %6.2f %%" % (new_y*100))

step=300, w1=0.8426, w2=-0.5997, b=-2.3907, loss=0.2694
step=600, w1=0.8348, w2=-0.3166, b=-3.8630, loss=0.1932
step=900, w1=0.7423, w2=0.0153, b=-4.9311, loss=0.1510
step=1200, w1=0.6372, w2=0.3245, b=-5.7765, loss=0.1235
step=1500, w1=0.5373, w2=0.5996, b=-6.4775, loss=0.1042
step=1800, w1=0.4471, w2=0.8421, b=-7.0768, loss=0.0900
step=2100, w1=0.3670, w2=1.0561, b=-7.6003, loss=0.0791
step=2400, w1=0.2962, w2=1.2458, b=-8.0652, loss=0.0705
step=2700, w1=0.2336, w2=1.4152, b=-8.4834, loss=0.0636
step=3000, w1=0.1779, w2=1.5675, b=-8.8635, loss=0.0579


InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_1' with dtype double and shape [?,1]
	 [[node Placeholder_1 (defined at <ipython-input-6-46ba9686d242>:3) ]]

Original stack trace for 'Placeholder_1':
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\ipykernel\kernelapp.py", line 597, in start
    self.io_loop.start()
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\tornado\platform\asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\asyncio\base_events.py", line 541, in run_forever
    self._run_once()
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\asyncio\base_events.py", line 1786, in _run_once
    handle._run()
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\ipykernel\kernelbase.py", line 545, in execute_request
    user_expressions, allow_stdin,
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\ipykernel\ipkernel.py", line 300, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\IPython\core\interactiveshell.py", line 2858, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\IPython\core\interactiveshell.py", line 2886, in _run_cell
    return runner(coro)
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\IPython\core\interactiveshell.py", line 3063, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\IPython\core\interactiveshell.py", line 3254, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-46ba9686d242>", line 3, in <module>
    Y = tf.placeholder(tf.float64, shape=[None, 1])
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 2718, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\ops\gen_array_ops.py", line 6031, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 742, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3322, in _create_op_internal
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1756, in __init__
    self._traceback = tf_stack.extract_stack()


# 계산으로 확인

In [16]:
m1 = np.array([7,6.]).reshape(1,2)
m1.shape

(1, 2)

In [17]:
m2 = np.array([0.1779, 1.5675]).reshape(2,1)
m2.shape

(2, 1)

In [18]:
np.matmul(m1, m2)

array([[10.6503]])

In [19]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [20]:
print(sigmoid(10.6503-8.8635))

0.8565344988956533
