# 폐암 수술 환자의 생존율 데이터 분석

In [1]:
import numpy as np
import tensorflow as tf
tf.__version__

'2.1.0'

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [3]:
# 실행할 때마다 같은 결과를 출력하기 위한 seed 값 설정
seed = 2020
np.random.seed(seed)
tf.random.set_seed(seed)

In [4]:
# 준비된 수술 환자 데이터를 불러들임
Data_set = np.loadtxt("dataset/ThoraricSurgery.csv", delimiter=",")
Data_set[:3, :]

array([[293.  ,   1.  ,   3.8 ,   2.8 ,   0.  ,   0.  ,   0.  ,   0.  ,
          0.  ,   0.  ,  12.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,
         62.  ,   0.  ],
       [  1.  ,   2.  ,   2.88,   2.16,   1.  ,   0.  ,   0.  ,   0.  ,
          1.  ,   1.  ,  14.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,
         60.  ,   0.  ],
       [  8.  ,   2.  ,   3.19,   2.5 ,   1.  ,   0.  ,   0.  ,   0.  ,
          1.  ,   0.  ,  11.  ,   0.  ,   0.  ,   1.  ,   1.  ,   0.  ,
         66.  ,   1.  ]])

In [5]:
# 환자의 기록과 수술 결과를 x와 y로 구분하여 저장
x_data = Data_set[:, 0:17]
y_data = Data_set[:, 17]
x_data.shape, y_data.shape

((470, 17), (470,))

In [15]:
x_data

array([[293.  ,   1.  ,   3.8 , ...,   1.  ,   0.  ,  62.  ],
       [  1.  ,   2.  ,   2.88, ...,   1.  ,   0.  ,  60.  ],
       [  8.  ,   2.  ,   3.19, ...,   1.  ,   0.  ,  66.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,   0.  ,  62.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,   0.  ,  58.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,   0.  ,  49.  ]])

In [16]:
y_data

array([0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0.

In [6]:
# 딥러닝 모델 설정
model = Sequential()
model.add(Dense(24, input_shape=(17,), activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 24)                432       
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 200       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 9         
Total params: 641
Trainable params: 641
Non-trainable params: 0
_________________________________________________________________


In [7]:
# 딥러닝 환경 설정 (오차함수, 최적화함수)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [13]:
# 딥너링 실행
model.fit(x_data, y_data, epochs=500, batch_size=1)

Train on 470 samples
Epoch 1/500
470/470 [==============================] - 1s 1ms/sample - loss: 0.7525 - accuracy: 0.8043
Epoch 2/500
470/470 [==============================] - 0s 834us/sample - loss: 0.5543 - accuracy: 0.8170
Epoch 3/500
470/470 [==============================] - 0s 836us/sample - loss: 0.5558 - accuracy: 0.8191
Epoch 4/500
470/470 [==============================] - 0s 835us/sample - loss: 0.4955 - accuracy: 0.8404
Epoch 5/500
470/470 [==============================] - 0s 848us/sample - loss: 0.5125 - accuracy: 0.8255
Epoch 6/500
470/470 [==============================] - 0s 849us/sample - loss: 0.5406 - accuracy: 0.8064
Epoch 7/500
470/470 [==============================] - 0s 839us/sample - loss: 0.4901 - accuracy: 0.8255
Epoch 8/500
470/470 [==============================] - 0s 830us/sample - loss: 0.4744 - accuracy: 0.8383
Epoch 9/500
470/470 [==============================] - 0s 857us/sample - loss: 0.5103 - accuracy: 0.8340
Epoch 10/500
470/470 [==============

470/470 [==============================] - 0s 854us/sample - loss: 0.3711 - accuracy: 0.8638
Epoch 78/500
470/470 [==============================] - 0s 844us/sample - loss: 0.3596 - accuracy: 0.8660
Epoch 79/500
470/470 [==============================] - 0s 830us/sample - loss: 0.3709 - accuracy: 0.8681
Epoch 80/500
470/470 [==============================] - 0s 837us/sample - loss: 0.3690 - accuracy: 0.8638 - loss: 0.3387 - accu
Epoch 81/500
470/470 [==============================] - 0s 843us/sample - loss: 0.3621 - accuracy: 0.8638
Epoch 82/500
470/470 [==============================] - 0s 833us/sample - loss: 0.3589 - accuracy: 0.8617
Epoch 83/500
470/470 [==============================] - 0s 841us/sample - loss: 0.3501 - accuracy: 0.8638
Epoch 84/500
470/470 [==============================] - 0s 833us/sample - loss: 0.3718 - accuracy: 0.8702
Epoch 85/500
470/470 [==============================] - 0s 837us/sample - loss: 0.3566 - accuracy: 0.8723
Epoch 86/500
470/470 [===============

470/470 [==============================] - 0s 834us/sample - loss: 0.3291 - accuracy: 0.8787
Epoch 154/500
470/470 [==============================] - 0s 847us/sample - loss: 0.3408 - accuracy: 0.8787
Epoch 155/500
470/470 [==============================] - 0s 839us/sample - loss: 0.3337 - accuracy: 0.8723
Epoch 156/500
470/470 [==============================] - 0s 842us/sample - loss: 0.3449 - accuracy: 0.8723
Epoch 157/500
470/470 [==============================] - 0s 835us/sample - loss: 0.3319 - accuracy: 0.8745
Epoch 158/500
470/470 [==============================] - 0s 831us/sample - loss: 0.3261 - accuracy: 0.8766
Epoch 159/500
470/470 [==============================] - 0s 828us/sample - loss: 0.3446 - accuracy: 0.8638
Epoch 160/500
470/470 [==============================] - 0s 840us/sample - loss: 0.3313 - accuracy: 0.8723
Epoch 161/500
470/470 [==============================] - 0s 837us/sample - loss: 0.3183 - accuracy: 0.8745
Epoch 162/500
470/470 [============================

470/470 [==============================] - 0s 840us/sample - loss: 0.3052 - accuracy: 0.8851
Epoch 230/500
470/470 [==============================] - 0s 834us/sample - loss: 0.3465 - accuracy: 0.8723
Epoch 231/500
470/470 [==============================] - 0s 840us/sample - loss: 0.3240 - accuracy: 0.8702
Epoch 232/500
470/470 [==============================] - 0s 836us/sample - loss: 0.3054 - accuracy: 0.8723
Epoch 233/500
470/470 [==============================] - 0s 846us/sample - loss: 0.3258 - accuracy: 0.8809
Epoch 234/500
470/470 [==============================] - 0s 819us/sample - loss: 0.3176 - accuracy: 0.8830
Epoch 235/500
470/470 [==============================] - 0s 834us/sample - loss: 0.3039 - accuracy: 0.8915
Epoch 236/500
470/470 [==============================] - 0s 835us/sample - loss: 0.3119 - accuracy: 0.8809
Epoch 237/500
470/470 [==============================] - 0s 837us/sample - loss: 0.3444 - accuracy: 0.8766
Epoch 238/500
470/470 [============================

470/470 [==============================] - 0s 831us/sample - loss: 0.3283 - accuracy: 0.8766
Epoch 306/500
470/470 [==============================] - 0s 852us/sample - loss: 0.3192 - accuracy: 0.8830
Epoch 307/500
470/470 [==============================] - 0s 829us/sample - loss: 0.2918 - accuracy: 0.8872
Epoch 308/500
470/470 [==============================] - 0s 834us/sample - loss: 0.3463 - accuracy: 0.8830
Epoch 309/500
470/470 [==============================] - 0s 845us/sample - loss: 0.3142 - accuracy: 0.8894
Epoch 310/500
470/470 [==============================] - 0s 835us/sample - loss: 0.3094 - accuracy: 0.8745
Epoch 311/500
470/470 [==============================] - 0s 825us/sample - loss: 0.2998 - accuracy: 0.8936
Epoch 312/500
470/470 [==============================] - 0s 834us/sample - loss: 0.3005 - accuracy: 0.8936
Epoch 313/500
470/470 [==============================] - 0s 843us/sample - loss: 0.3175 - accuracy: 0.8787
Epoch 314/500
470/470 [============================

470/470 [==============================] - 0s 819us/sample - loss: 0.2918 - accuracy: 0.8830
Epoch 382/500
470/470 [==============================] - 0s 843us/sample - loss: 0.3251 - accuracy: 0.8851
Epoch 383/500
470/470 [==============================] - 0s 835us/sample - loss: 0.3082 - accuracy: 0.8766
Epoch 384/500
470/470 [==============================] - 0s 837us/sample - loss: 0.2941 - accuracy: 0.8830
Epoch 385/500
470/470 [==============================] - 0s 830us/sample - loss: 0.2910 - accuracy: 0.8957
Epoch 386/500
470/470 [==============================] - 0s 838us/sample - loss: 0.2920 - accuracy: 0.8979
Epoch 387/500
470/470 [==============================] - 0s 835us/sample - loss: 0.2965 - accuracy: 0.8809
Epoch 388/500
470/470 [==============================] - 0s 845us/sample - loss: 0.3052 - accuracy: 0.8872
Epoch 389/500
470/470 [==============================] - 0s 834us/sample - loss: 0.3058 - accuracy: 0.8872
Epoch 390/500
470/470 [============================

470/470 [==============================] - 0s 866us/sample - loss: 0.2992 - accuracy: 0.8915
Epoch 458/500
470/470 [==============================] - 0s 880us/sample - loss: 0.2876 - accuracy: 0.8915
Epoch 459/500
470/470 [==============================] - 0s 873us/sample - loss: 0.2925 - accuracy: 0.8915
Epoch 460/500
470/470 [==============================] - 0s 843us/sample - loss: 0.3092 - accuracy: 0.8766
Epoch 461/500
470/470 [==============================] - 0s 859us/sample - loss: 0.2833 - accuracy: 0.8872
Epoch 462/500
470/470 [==============================] - 0s 862us/sample - loss: 0.2756 - accuracy: 0.8872
Epoch 463/500
470/470 [==============================] - 0s 838us/sample - loss: 0.2827 - accuracy: 0.8936
Epoch 464/500
470/470 [==============================] - 0s 847us/sample - loss: 0.2950 - accuracy: 0.8894
Epoch 465/500
470/470 [==============================] - 0s 838us/sample - loss: 0.2903 - accuracy: 0.8915
Epoch 466/500
470/470 [============================

In [14]:
model.evaluate(x_data, y_data, verbose=2)[1]

470/470 - 0s - loss: 0.2596 - accuracy: 0.9064


0.906383