# 폐암 수술 환자의 생존율 데이터 분석

In [1]:
import os
os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"

In [2]:
import numpy as np
import tensorflow as tf
tf.__version__

'2.1.0'

In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [4]:
# 실행할 때마다 같은 결과를 출력하기 위한 seed 값 설정
seed = 2020
np.random.seed(seed)
tf.random.set_seed(seed)

In [5]:
# 준비된 수술 환자 데이터를 불러들임
Data_set = np.loadtxt("dataset/ThoraricSurgery.csv", delimiter=",")
Data_set[:3, :]

array([[293.  ,   1.  ,   3.8 ,   2.8 ,   0.  ,   0.  ,   0.  ,   0.  ,
          0.  ,   0.  ,  12.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,
         62.  ,   0.  ],
       [  1.  ,   2.  ,   2.88,   2.16,   1.  ,   0.  ,   0.  ,   0.  ,
          1.  ,   1.  ,  14.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,
         60.  ,   0.  ],
       [  8.  ,   2.  ,   3.19,   2.5 ,   1.  ,   0.  ,   0.  ,   0.  ,
          1.  ,   0.  ,  11.  ,   0.  ,   0.  ,   1.  ,   1.  ,   0.  ,
         66.  ,   1.  ]])

In [6]:
# 환자의 기록과 수술 결과를 x와 y로 구분하여 저장
x_data = Data_set[:, 0:17]
y_data = Data_set[:, 17]
x_data.shape, y_data.shape

((470, 17), (470,))

In [7]:
x_data

array([[293.  ,   1.  ,   3.8 , ...,   1.  ,   0.  ,  62.  ],
       [  1.  ,   2.  ,   2.88, ...,   1.  ,   0.  ,  60.  ],
       [  8.  ,   2.  ,   3.19, ...,   1.  ,   0.  ,  66.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,   0.  ,  62.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,   0.  ,  58.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,   0.  ,  49.  ]])

In [8]:
y_data

array([0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0.

In [7]:
# 딥러닝 모델 설정
model = Sequential()
model.add(Dense(100, input_shape=(17,), activation='relu'))
model.add(Dense(60, activation='relu'))
model.add(Dense(30, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 100)               1800      
_________________________________________________________________
dense_1 (Dense)              (None, 60)                6060      
_________________________________________________________________
dense_2 (Dense)              (None, 30)                1830      
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 31        
Total params: 9,721
Trainable params: 9,721
Non-trainable params: 0
_________________________________________________________________


In [8]:
# 딥러닝 환경 설정 (오차함수, 최적화함수)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [9]:
# 딥너링 실행
model.fit(x_data, y_data, epochs=250, batch_size=5)

Train on 470 samples
Epoch 1/250
470/470 [==============================] - 1s 1ms/sample - loss: 0.9747 - accuracy: 0.7894
Epoch 2/250
470/470 [==============================] - 0s 174us/sample - loss: 0.5366 - accuracy: 0.8191
Epoch 3/250
470/470 [==============================] - 0s 174us/sample - loss: 0.6288 - accuracy: 0.8085
Epoch 4/250
470/470 [==============================] - 0s 172us/sample - loss: 0.5023 - accuracy: 0.8319
Epoch 5/250
470/470 [==============================] - 0s 176us/sample - loss: 0.5987 - accuracy: 0.8085
Epoch 6/250
470/470 [==============================] - 0s 180us/sample - loss: 0.4728 - accuracy: 0.8404
Epoch 7/250
470/470 [==============================] - 0s 174us/sample - loss: 0.5334 - accuracy: 0.8234
Epoch 8/250
470/470 [==============================] - 0s 176us/sample - loss: 0.5957 - accuracy: 0.8404
Epoch 9/250
470/470 [==============================] - 0s 170us/sample - loss: 0.5384 - accuracy: 0.8383
Epoch 10/250
470/470 [==============

In [10]:
model.evaluate(x_data, y_data, verbose=2)[1]

470/470 - 0s - loss: 0.2973 - accuracy: 0.8872


0.88723403