# 폐암 수술 환자의 생존율 데이터 분석

In [1]:
import os
os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"

In [2]:
import numpy as np
import tensorflow as tf
tf.__version__

'2.1.0'

In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [4]:
# 실행할 때마다 같은 결과를 출력하기 위한 seed 값 설정
seed = 2020
np.random.seed(seed)
tf.random.set_seed(seed)

In [5]:
# 준비된 수술 환자 데이터를 불러들임
Data_set = np.loadtxt("dataset/ThoraricSurgery.csv", delimiter=",")
Data_set[:3, :]

array([[293.  ,   1.  ,   3.8 ,   2.8 ,   0.  ,   0.  ,   0.  ,   0.  ,
          0.  ,   0.  ,  12.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,
         62.  ,   0.  ],
       [  1.  ,   2.  ,   2.88,   2.16,   1.  ,   0.  ,   0.  ,   0.  ,
          1.  ,   1.  ,  14.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,
         60.  ,   0.  ],
       [  8.  ,   2.  ,   3.19,   2.5 ,   1.  ,   0.  ,   0.  ,   0.  ,
          1.  ,   0.  ,  11.  ,   0.  ,   0.  ,   1.  ,   1.  ,   0.  ,
         66.  ,   1.  ]])

In [6]:
# 환자의 기록과 수술 결과를 x와 y로 구분하여 저장
x_data = Data_set[:, 0:17]
y_data = Data_set[:, 17]
x_data.shape, y_data.shape

((470, 17), (470,))

In [7]:
x_data

array([[293.  ,   1.  ,   3.8 , ...,   1.  ,   0.  ,  62.  ],
       [  1.  ,   2.  ,   2.88, ...,   1.  ,   0.  ,  60.  ],
       [  8.  ,   2.  ,   3.19, ...,   1.  ,   0.  ,  66.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,   0.  ,  62.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,   0.  ,  58.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,   0.  ,  49.  ]])

In [8]:
y_data

array([0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0.

In [9]:
# 딥러닝 모델 설정
model = Sequential()
model.add(Dense(100, input_shape=(17,), activation='relu'))
model.add(Dense(70, activation='relu'))
model.add(Dense(30, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 100)               1800      
_________________________________________________________________
dense_1 (Dense)              (None, 70)                7070      
_________________________________________________________________
dense_2 (Dense)              (None, 30)                2130      
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 31        
Total params: 11,031
Trainable params: 11,031
Non-trainable params: 0
_________________________________________________________________


In [10]:
# 딥러닝 환경 설정 (오차함수, 최적화함수)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [11]:
# 딥너링 실행
model.fit(x_data, y_data, epochs=250, batch_size=5)

Train on 470 samples
Epoch 1/250
470/470 [==============================] - 0s 763us/sample - loss: 1.4725 - accuracy: 0.7723
Epoch 2/250
470/470 [==============================] - 0s 166us/sample - loss: 0.5568 - accuracy: 0.8277
Epoch 3/250
470/470 [==============================] - 0s 173us/sample - loss: 0.6572 - accuracy: 0.7957
Epoch 4/250
470/470 [==============================] - 0s 169us/sample - loss: 0.5234 - accuracy: 0.8277
Epoch 5/250
470/470 [==============================] - 0s 174us/sample - loss: 0.6378 - accuracy: 0.8085
Epoch 6/250
470/470 [==============================] - 0s 168us/sample - loss: 0.4888 - accuracy: 0.8362
Epoch 7/250
470/470 [==============================] - 0s 171us/sample - loss: 0.5401 - accuracy: 0.8277
Epoch 8/250
470/470 [==============================] - 0s 169us/sample - loss: 0.5845 - accuracy: 0.8362
Epoch 9/250
470/470 [==============================] - 0s 160us/sample - loss: 0.5462 - accuracy: 0.8362
Epoch 10/250
470/470 [============

470/470 [==============================] - 0s 161us/sample - loss: 0.3924 - accuracy: 0.8617
Epoch 79/250
470/470 [==============================] - 0s 158us/sample - loss: 0.4005 - accuracy: 0.8553
Epoch 80/250
470/470 [==============================] - 0s 161us/sample - loss: 0.3967 - accuracy: 0.8553
Epoch 81/250
470/470 [==============================] - 0s 147us/sample - loss: 0.3978 - accuracy: 0.8638
Epoch 82/250
470/470 [==============================] - 0s 158us/sample - loss: 0.3863 - accuracy: 0.8638
Epoch 83/250
470/470 [==============================] - 0s 157us/sample - loss: 0.3882 - accuracy: 0.8617
Epoch 84/250
470/470 [==============================] - 0s 153us/sample - loss: 0.3830 - accuracy: 0.8638
Epoch 85/250
470/470 [==============================] - 0s 142us/sample - loss: 0.3901 - accuracy: 0.8596
Epoch 86/250
470/470 [==============================] - 0s 152us/sample - loss: 0.3799 - accuracy: 0.8681
Epoch 87/250
470/470 [==============================] - 0s 

470/470 [==============================] - 0s 174us/sample - loss: 0.3377 - accuracy: 0.8723
Epoch 155/250
470/470 [==============================] - 0s 170us/sample - loss: 0.3511 - accuracy: 0.8638
Epoch 156/250
470/470 [==============================] - 0s 170us/sample - loss: 0.3420 - accuracy: 0.8745
Epoch 157/250
470/470 [==============================] - 0s 167us/sample - loss: 0.3365 - accuracy: 0.8745
Epoch 158/250
470/470 [==============================] - 0s 168us/sample - loss: 0.3366 - accuracy: 0.8745
Epoch 159/250
470/470 [==============================] - 0s 170us/sample - loss: 0.3289 - accuracy: 0.8766
Epoch 160/250
470/470 [==============================] - 0s 170us/sample - loss: 0.3468 - accuracy: 0.8723
Epoch 161/250
470/470 [==============================] - 0s 167us/sample - loss: 0.3350 - accuracy: 0.8766
Epoch 162/250
470/470 [==============================] - 0s 169us/sample - loss: 0.3435 - accuracy: 0.8723
Epoch 163/250
470/470 [============================

470/470 [==============================] - 0s 170us/sample - loss: 0.2909 - accuracy: 0.8936
Epoch 231/250
470/470 [==============================] - 0s 170us/sample - loss: 0.3064 - accuracy: 0.8872
Epoch 232/250
470/470 [==============================] - 0s 170us/sample - loss: 0.3638 - accuracy: 0.8681
Epoch 233/250
470/470 [==============================] - ETA: 0s - loss: 0.3314 - accuracy: 0.87 - 0s 169us/sample - loss: 0.3388 - accuracy: 0.8745
Epoch 234/250
470/470 [==============================] - 0s 168us/sample - loss: 0.3145 - accuracy: 0.8957
Epoch 235/250
470/470 [==============================] - 0s 166us/sample - loss: 0.3209 - accuracy: 0.8894
Epoch 236/250
470/470 [==============================] - 0s 165us/sample - loss: 0.3110 - accuracy: 0.8766
Epoch 237/250
470/470 [==============================] - 0s 167us/sample - loss: 0.3094 - accuracy: 0.8766
Epoch 238/250
470/470 [==============================] - 0s 168us/sample - loss: 0.3599 - accuracy: 0.8723
Epoch 239

In [12]:
model.evaluate(x_data, y_data, verbose=2)[1]

470/470 - 0s - loss: 0.3246 - accuracy: 0.8830


0.88297874